import express from "express";

export const Register=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};

export const FetchProfile=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};

export const UpdateProfile=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};

export const Delete=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};

export const FetchAll=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};

export const Login=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};

export const ChangePassword=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};

export const ForgotPassword=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};

export const ResetPassword=async(request: express.Request, reponse: express.Response)=>{
    try{

    }catch(err:unknown){
        reponse.status(500).json({
            "message":"Internal Server Error",
            "error": err,
        });
    }
};